name: "godot-ci export"
on:
  push:
    branches:
      - main

env:
  GODOT_VERSION: 4.0.1
  EXPORT_NAME: gg4
  ITCH_GAME: gg4
  ITCH_USER: erebrus

jobs:
  export-web:
    name: Web Export
    runs-on: ubuntu-latest
    container:
      image: seanmaxwell/godot-ci:4.0.1
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        lfs: true
    - name: Setup
      run: |
        mkdir -v -p ~/.local/share/godot/export_templates
        mv /root/.local/share/godot/templates/${GODOT_VERSION}.stable ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable
        ls ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable
    - name: Web Build
      run: |
        mkdir -v -p build/html
        cd src
        godot -v --headless --export-release "HTML5" ../build/html/index.html
    - name: Publish to Itch.io
      uses: josephbmanley/butler-publish-itchio-action@master
      env:
        BUTLER_CREDENTIALS: ${{ secrets.BUTLER_API_KEY }}
        CHANNEL: web
        PACKAGE: build/html
